accessLog:
  filePath: "/var/log/traefik/access.log"
  format: "json"

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "secure"
          scheme: "https"
  secure:
    address: ":443"

global:
  sendAnonymousUsage: false

log:
  filePath: "/var/log/traefik/traefik.log"
  format: "json"
  level: "DEBUG"

providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

serversTransport:
  insecureSkipVerify: true